version: "3.7"
services:
  db:
    image: postgres:15
    container_name: bookshelf_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: bookshelf_redis

  bookshelf:
    image: bookshelf_src
    build:
      context: .
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/bookshelf/docker/src.sh"]
    ports:
      - 7777:8000